### ISSUE TITLE
When wrong, show the correct flag along the correct name

### ISSUE THREAD

**Issue by ruihildt** [billywojcicki/vexillologist#1]
When you make a wrong guess:
- a message with the correct country name appears
- simultaneously, the flag changes to the next guess

This means the user making a wrong guess never sees the correct flag along the correct name, making it hard to try to remember the association.

This frustrates me enough to stop playing the game altogether and file an issue. 😃

**Comment by bwojcicki** [comment]
Hi @ruihildt, thanks for the feedback! I made some changes and pushed an update that should resolve your issue.
